// This file has been auto-generated by model-interfaces/openapi repository. Please do not update it manually.
        import { constants } from "@owlgrid-dev/constants";
import { OperationType } from "@owlgrid-dev/types";
import { createOrganization } from '../controllers/createOrganization';
import { getOrganization } from '../controllers/getOrganization';
import { listOrganizations } from '../controllers/listOrganizations';

        export const operations = [{
                serviceName: constants.administration.name,
                operationType: 'create' as OperationType,
                operationPath: '/organizations',
                operationName: 'createOrganization',
                operationId: 'administration.organizations.create',
                createController: createOrganization
            },
{
                serviceName: constants.administration.name,
                operationType: 'get' as OperationType,
                operationPath: '/organizations/{id}',
                operationName: 'getOrganization',
                operationId: 'administration.organizations.get',
                getController: getOrganization
            },
{
                serviceName: constants.administration.name,
                operationType: 'list' as OperationType,
                operationPath: '/organizations',
                operationName: 'listOrganizations',
                operationId: 'administration.organizations.list',
                listController: listOrganizations
            }];