/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    mainSidebar: [
        {
            type: 'autogenerated',
            dirName: 'general'
        },
        // Divider
        {
            type: 'html',
            value:
                '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 1rem 0 0.5rem 1rem;" />',
        },
        //  title
        {
            type: 'html',
            value: '<b>Resources</b>',
            defaultStyle: true,
        },
        {
            type: 'autogenerated',
            dirName: 'resources'
        },
        // Divider
        {
            type: 'html',
            value:
                '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 1rem 0 0.5rem 1rem;" />',
        },
        //  title
        {
            type: 'html',
            value: '<b>References</b>',
            defaultStyle: true,
        },
        {
            type: 'autogenerated',
            dirName: 'references'
        },
        // Divider
        {
            type: 'html',
            value:
                '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 1rem 0 0.5rem 1rem;" />',
        },
        // Title
        {
            type: 'html',
            value: '<b>Developers</b>',
            defaultStyle: true,
        },
        {
            type: 'autogenerated',
            dirName: 'developers'
        }
    ]
};

module.exports = sidebars;
