module.exports = {
    tutorialSidebar: [
        {
            type: 'autogenerated',
            dirName: 'general'
        },
        // Divider
        {
            type: 'html',
            value:
                '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 1rem 0 0.5rem 1rem;" />',
        },
        //  title
        {
            type: 'html',
            value: '<b>Resources</b>',
            defaultStyle: true,
        },
        {
            type: 'autogenerated',
            dirName: 'resources'
        },
        // Divider
        {
            type: 'html',
            value:
                '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 1rem 0 0.5rem 1rem;" />',
        },
        //  title
        {
            type: 'html',
            value: '<b>References</b>',
            defaultStyle: true,
        },

        {
            type: 'autogenerated',
            dirName: 'references'
        }
    ]
};
