/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    tutorialSidebar: [
        { type: 'autogenerated', dirName: '.' },
        //  title
        {
            type: 'html',
            value: '<b>Resources</b>',
            defaultStyle: true,
        },
        // Divider
        {
            type: 'html',
            value:
                '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 0.5rem 0 0.25rem 1rem;" />',
        },
        {
            type: 'category',
            label: 'Tutorial',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'concepts',
                }
            ]
        }]

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      {
        type: 'category',
        label: 'Tutorial',
        items: ['hello'],
      },
    ],
  
  
    -> Divider
   {
             type: 'html',
             value:
               '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 0.5rem 0 0.25rem 1rem;" />',
           },
  
  
     */
};
